name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: tentative-app
          path: |
            ./
            !var/*
            !.git
            !vendor

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: tentative-app

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: vps-f9de4d18.vps.ovh.net
          username: "tentatives"
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "./*"
          target: "/home/tentatives/prod"

      - name: Update schema database
        uses: appleboy/ssh-action@master
        with:
          host: vps-f9de4d18.vps.ovh.net
          username: tentatives
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: cd /home/tentatives/prod && composer install && php bin/console d:s:u --force
