name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: vps-f9de4d18.vps.ovh.net
          username: "tentatives"
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "./*"
          target: "/home/tentatives/test"

#      - name: Install dependencies
#        run: composer install

      - name: Schema Database update
        uses: appleboy/ssh-action@master
        with:
          host: vps-f9de4d18.vps.ovh.net
          username: tentatives
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: php /home/tentatives/test/bin/console d:s:u --force && php /home/tentatives/test/bin/console d:f:l --no-interaction

